### ISSUE TITLE
Rendering with `@testing-library/react` causes many `act` warnings

### ISSUE THREAD

**Issue by sophyphreak** [inovua/reactdatagrid#286]
- what edition are you using - **community** 
- version for `@inovua/reactdatagrid-community` - 4.19.7

Relevant code or config

```javascript
// App.test.js

import App from "./App";
import { render } from "@testing-library/react";

test(`should render App`, () => {
  render(<App />);
});
```

What you did:
I tried to render the data grid in a test environment with @testing-library/react

What happened:
I got a lot of `act` warnings, which is not expected behavior. All are identical:
```bash
console.error
    Warning: An update to null inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at /Users/andrewhorn/workspace/reactdatagrid-example/node_modules/@inovua/reactdatagrid-community/factory.js:218:41
        at TheGrid (/Users/andrewhorn/workspace/reactdatagrid-example/node_modules/@inovua/reactdatagrid-community/factory.js:1659:43)
        at div
        at App (/Users/andrewhorn/workspace/reactdatagrid-example/src/App.js:79:39)
        at _default

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at dispatchSetState (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at node_modules/@inovua/reactdatagrid-community/hooks/useNamedState.js:38:5
      at node_modules/@inovua/reactdatagrid-community/hooks/useDataSource/index.js:867:11
```

Reproduction repository:

https://github.com/sophyphreak/reactdatagrid-example

If this doesn't give the `act` warnings, add a few tests until they appear. Things like `expect(screen.getByText(/germany/i).toBeInTheDocument()`)

Problem description:

The `act` warnings appear to be originating inside the `ReactDataGrid` component. These warnings make testing correctly much harder for the developer because these warnings exist to make sure the developer is testing everything they should.

Suggested solution:

I'm sorry, I don't have one.

**Comment by sophyphreak** [comment]
This is what I ended up doing:
```js
import App from "./App";
import { render } from "@testing-library/react";
import { act } from "react-dom/test-utils";

test(`should render App`, async () => {
  const promise = Promise.resolve();
  render(<App />);
  await act(async () => {
    await promise;
  });
});
```
I think it's good enough for me.
