### ISSUE TITLE
filteredRowsCount usage produces react warning

### ISSUE THREAD

**Issue by AndrewBoklashko** [inovua/reactdatagrid#343]
Sandbox: https://codesandbox.io/s/reactdatagrid-filteredrowscount-issue-gq42p5?file=/src/App.js

Steps to reproduce the issue:

1. Open the sandbox link
2. Open the sandbox console

Expected result: no console errors
Actual result:
```
Warning: Cannot update a component (`App`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at eval (https://gq42p5.csb.app/node_modules/@inovua/reactdatagrid-community/factory.js:162:41)
    at TheGrid (https://gq42p5.csb.app/node_modules/@inovua/reactdatagrid-community/factory.js:1386:43)
    at div
    at App (https://gq42p5.csb.app/src/App.js:35:41)
    at _default
```

Related issue: https://github.com/inovua/reactdatagrid/issues/340

**Comment by AndrewBoklashko** [comment]
Any updates?
