### ISSUE TITLE
Nested object's properties map to column

### ISSUE THREAD

**Issue by robozb** [inovua/reactdatagrid#352]
Dear Developers, 

How can I map a nested object's properies to data grid colums?

For example this:

```
{
    "id": 65,
    "employee": {
        "id": 24,
        "name": "Van Jast",
        "email": "freddy.beatty@hotmail.com",
        "address": "37204 Toni Islands",
        "city": "Blaketown",
        "state": "Massachusetts",
        "zipCode": "03395-2948",
        "phone": "035.260.8830",
    },
    "hotel": {
        "id": 491,
        "companyName": "Treutel Group",
        "address": "535 Sonya Wall",
        "city": "Lake Basil",
        "state": "Wisconsin",
        "zipCode": "59389-9353",
        "firstWorkDay": "MONDAY"
    },
    "hourlyRate": 45.3127,
    "overTime": 67.969,
    "beginning": "2023-01-21",
    "ending": "2023-03-09",
    "commitmentSignedUp": true,
    "commitmentAmount": 126.836,
    "commitmentDays": 42
}
```

Thank you so much!

**Comment by robozb** [comment]
I can do this to reach the "inner" properties at column definition:

```
{ 
    name: "employee", header: "Employee ID", visible: true, width: 100, 
    render: ({data}) => {
        return data.id;
    }
},

{ 
    name: "hotel", header: "Hotel ID", visible: true, width: 100,
    render: ({data}) => {
        return data.id;
    }
}
```

![image](https://user-images.githubusercontent.com/8656998/222419295-5459cdf8-36b4-434d-854a-ac6dfa29e196.png)

**Comment by robozb** [comment]
But in this case the system throws this exception: 

```
{ 
    name: "employee", header: "Employee ID", visible: true, width: 100, 
    render: ({data}) => {
        return data.id;
    }
},

{ 
    name: "employee", header: "Employee NAME", visible: true, width: 100, 
    render: ({data}) => {
        return data.name;
    }
},
```

```
react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {id, name, email, address, city, state, zipCode, phone, comment}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19167:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
```

**Comment by robozb** [comment]
OK, thank you so much, I could solve it :) on this way: 

```
{ 
    name: "employee_id", header: "Employee ID", visible: true, width: 200, 
    render: ({data}) => {
        return data.employee.id;
    }
},

{ 
    name: "employee_name", header: "Employee NAME", visible: true, width: 200, 
    render: ({data}) => {
        return data.employee.name;
    }
},   

{ 
    name: "hotel_id", header: "Hotel ID", visible: true, width: 200, 
    render: ({data}) => {
        return data.hotel.id;
    }
},     

{ 
    name: "hotel_companyName", header: "Hotel Company Name", visible: true, width: 200, 
    render: ({data}) => {
        return data.hotel.companyName;
    }
},
```

![image](https://user-images.githubusercontent.com/8656998/222423820-6bddbdab-e2a9-443e-ab06-9f09e01842f5.png)
